/**
 * Markdown sanitization infrastructure (SEC-01 defense-in-depth).
 *
 * Two layers:
 * 1. sanitizeMarkdown() -- DOMPurify pre-sanitization strips ALL HTML from raw
 *    markdown body before it enters the remark/rehype pipeline.
 * 2. sanitizeSchema -- Extended rehype-sanitize schema that allows only the
 *    classes/attributes generated by trusted plugins (highlight.js, callouts).
 */
import DOMPurify from "dompurify";
import { defaultSchema } from "rehype-sanitize";
import type { Schema } from "hast-util-sanitize";

/**
 * Pre-sanitize raw markdown body with DOMPurify.
 *
 * Strips ALL HTML tags while keeping their text content intact.
 * This is the first layer of defense -- markdown syntax (headers, links,
 * code blocks, etc.) passes through unmodified because it is plain text,
 * while any embedded `<script>`, `<iframe>`, or other HTML is stripped.
 *
 * @param rawBody - Raw markdown string (may contain embedded HTML)
 * @returns Sanitized markdown string with all HTML tags removed
 */
export function sanitizeMarkdown(rawBody: string): string {
  return DOMPurify.sanitize(rawBody, {
    ALLOWED_TAGS: [],
    KEEP_CONTENT: true,
  });
}

/**
 * Extended rehype-sanitize schema for the markdown rendering pipeline.
 *
 * Starts from the GitHub-style defaultSchema and adds allowances for:
 * - highlight.js syntax classes (hljs-*, language-*) on code/span elements
 * - rehype-callouts data attributes and class names on all elements
 * - <details>/<summary> tags for foldable callouts (already in default)
 *
 * This is the second layer of defense -- after remark/rehype plugins
 * transform markdown into HTML AST, this schema strips anything that
 * was not explicitly allowed.
 */
export const sanitizeSchema: Schema = {
  ...defaultSchema,
  attributes: {
    ...defaultSchema.attributes,
    // Allow highlight.js language classes on code elements
    // (extends existing language-* pattern from default)
    code: [
      ...(defaultSchema.attributes?.code ?? []),
      ["className", /^language-/],
    ],
    // Allow highlight.js token classes on span elements
    span: [
      ...(defaultSchema.attributes?.span ?? []),
      ["className", /^hljs-/],
    ],
    // Allow callout data attributes on all elements
    "*": [
      ...(defaultSchema.attributes?.["*"] ?? []),
      "dataCallout",
      "dataCalloutType",
      "dataCalloutTitle",
      "dataCalloutBody",
      "dataCalloutFoldable",
      "dataCollapsible",
    ],
  },
  // defaultSchema already includes 'details' and 'summary' in tagNames
  tagNames: [...(defaultSchema.tagNames ?? [])],
};
