"""command_management_tables

Revision ID: e7b1c3f25b7a
Revises: 309f0dad26b4
Create Date: 2026-02-02 12:00:00.000000
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e7b1c3f25b7a"
down_revision: Union[str, None] = "309f0dad26b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())
    if "_alembic_tmp_commands" in existing_tables:
        op.drop_table("_alembic_tmp_commands")
        existing_tables.remove("_alembic_tmp_commands")

    if "commands" not in existing_tables:
        op.create_table(
            "commands",
            sa.Column("id", sa.String(), nullable=False),
            sa.Column("name", sa.String(), nullable=False),
            sa.Column("category", sa.String(), nullable=False),
            sa.Column("command", sa.Text(), nullable=False),
            sa.Column("description", sa.Text(), nullable=True),
            sa.Column("tags", sa.JSON(), nullable=False),
            sa.Column("is_custom", sa.Boolean(), nullable=False),
            sa.Column(
                "scope",
                sa.String(),
                server_default="global",
                nullable=False,
            ),
            sa.Column("project_id", sa.String(), nullable=True),
            sa.ForeignKeyConstraint(["project_id"], ["projects.id"]),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(
            "ix_commands_project_id",
            "commands",
            ["project_id"],
            unique=False,
        )
        existing_tables.add("commands")
        command_columns = {
            "id",
            "name",
            "category",
            "command",
            "description",
            "tags",
            "is_custom",
            "scope",
            "project_id",
        }
        command_indexes = {"ix_commands_project_id"}
        has_project_fk = True
    else:
        command_columns = {
            col["name"] for col in inspector.get_columns("commands")
        }
        command_indexes = {
            idx["name"] for idx in inspector.get_indexes("commands") if idx.get("name")
        }
        command_fks = inspector.get_foreign_keys("commands")
        has_project_fk = any(
            fk.get("referred_table") == "projects"
            and fk.get("constrained_columns") == ["project_id"]
            for fk in command_fks
        )

    category_indexes = {
        idx["name"]
        for idx in inspector.get_indexes("command_categories")
        if idx.get("name")
    } if "command_categories" in existing_tables else set()
    filter_indexes = {
        idx["name"]
        for idx in inspector.get_indexes("command_filters")
        if idx.get("name")
    } if "command_filters" in existing_tables else set()

    needs_scope = "scope" not in command_columns
    needs_project_id = "project_id" not in command_columns
    needs_index = "ix_commands_project_id" not in command_indexes

    if needs_scope or needs_project_id or needs_index or not has_project_fk:
        with op.batch_alter_table("commands") as batch_op:
            if needs_scope:
                batch_op.add_column(
                    sa.Column("scope", sa.String(), server_default="global", nullable=False)
                )
            if needs_project_id:
                batch_op.add_column(sa.Column("project_id", sa.String(), nullable=True))
            if not has_project_fk:
                batch_op.create_foreign_key(
                    "fk_commands_project_id",
                    "projects",
                    ["project_id"],
                    ["id"],
                )
            if needs_index:
                batch_op.create_index(
                    "ix_commands_project_id",
                    ["project_id"],
                    unique=False,
                )

    if "command_favorites" not in existing_tables:
        op.create_table(
            "command_favorites",
            sa.Column("id", sa.String(), nullable=False),
            sa.Column("user_id", sa.String(), nullable=False),
            sa.Column("command_id", sa.String(), nullable=False),
            sa.Column("project_id", sa.String(), nullable=True),
            sa.ForeignKeyConstraint(["command_id"], ["commands.id"]),
            sa.ForeignKeyConstraint(["project_id"], ["projects.id"]),
            sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint(
                "user_id",
                "command_id",
                "project_id",
                name="uq_command_favorites_user_command_project",
            ),
        )

    if "command_categories" not in existing_tables:
        op.create_table(
            "command_categories",
            sa.Column("id", sa.String(), nullable=False),
            sa.Column("name", sa.String(), nullable=False),
            sa.Column("scope", sa.String(), nullable=False),
            sa.Column("project_id", sa.String(), nullable=True),
            sa.Column("sort_order", sa.Integer(), nullable=True),
            sa.ForeignKeyConstraint(["project_id"], ["projects.id"]),
            sa.PrimaryKeyConstraint("id"),
        )
    if "ix_command_categories_project_id" not in category_indexes:
        op.create_index(
            "ix_command_categories_project_id",
            "command_categories",
            ["project_id"],
            unique=False,
        )

    if "command_filters" not in existing_tables:
        op.create_table(
            "command_filters",
            sa.Column("id", sa.String(), nullable=False),
            sa.Column("name", sa.String(), nullable=False),
            sa.Column("scope", sa.String(), nullable=False),
            sa.Column("project_id", sa.String(), nullable=True),
            sa.Column("sort_order", sa.Integer(), nullable=True),
            sa.ForeignKeyConstraint(["project_id"], ["projects.id"]),
            sa.PrimaryKeyConstraint("id"),
        )
    if "ix_command_filters_project_id" not in filter_indexes:
        op.create_index(
            "ix_command_filters_project_id",
            "command_filters",
            ["project_id"],
            unique=False,
        )

    if "command_variables" not in existing_tables:
        op.create_table(
            "command_variables",
            sa.Column("id", sa.String(), nullable=False),
            sa.Column("user_id", sa.String(), nullable=False),
            sa.Column("key", sa.String(), nullable=False),
            sa.Column("value", sa.Text(), nullable=False),
            sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("user_id", "key", name="uq_command_variables_user_key"),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("command_variables")

    op.drop_index("ix_command_filters_project_id", table_name="command_filters")
    op.drop_table("command_filters")

    op.drop_index("ix_command_categories_project_id", table_name="command_categories")
    op.drop_table("command_categories")

    op.drop_table("command_favorites")

    bind = op.get_bind()
    inspector = sa.inspect(bind)
    command_columns = {col["name"] for col in inspector.get_columns("commands")}
    command_indexes = {
        idx["name"] for idx in inspector.get_indexes("commands") if idx.get("name")
    }
    command_fks = inspector.get_foreign_keys("commands")
    has_project_fk = any(
        fk.get("referred_table") == "projects"
        and fk.get("constrained_columns") == ["project_id"]
        for fk in command_fks
    )

    if (
        "scope" in command_columns
        or "project_id" in command_columns
        or "ix_commands_project_id" in command_indexes
        or has_project_fk
    ):
        with op.batch_alter_table("commands") as batch_op:
            if "ix_commands_project_id" in command_indexes:
                batch_op.drop_index("ix_commands_project_id")
            if has_project_fk:
                batch_op.drop_constraint("fk_commands_project_id", type_="foreignkey")
            if "project_id" in command_columns:
                batch_op.drop_column("project_id")
            if "scope" in command_columns:
                batch_op.drop_column("scope")
    # ### end Alembic commands ###
